=== JonAnderBeroz/SzaWeb/xml/tasks.dtd
<!ELEMENT tasks (task)*> <!--The file will be composed by a set of tasks-->
<!ELEMENT task (author,text,list)> <!-- Each task will have an author a text and a list(the list could be the theme also ex Shoping)-->
<!ATTLIST task important CDATA #REQUIRED> <!-- The task will have and atribute to set if the task is important or not-->
<!ELEMENT author (#PCDATA)> <!--The author of the task will be the current logged user and will be set automatically-->
<!ELEMENT text (#PCDATA)> <!--The text will be the task itself-->
<!ELEMENT list (#PCDATA)> <!-- The list will be were the task belongs, default will be main and the creating of list may be inplemented-->

=== JonAnderBeroz/SzaWeb/xml/tasks.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no" ?>
<!DOCTYPE tasks SYSTEM 'tasks.dtd'>
<tasks>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
    <task>
        <text>prueba</text>
    </task>
</tasks>
